export const response = {
  FormId: 140,
  CityId: 1,
  FormValues: [
    {
      ParameterId: 4,
      ParameterName: "Year Built",
      value: '"1990"',
      Phase: "Site Information",
      ParameterTypeId: "2",
      ParamOrder: "12",
    },
    {
      ParameterId: 5,
      ParameterName: "Lot Size",
      value: '"5000"',
      Phase: "Site Information",
      ParameterTypeId: "2",
      ParamOrder: "5",
    },
    {
      ParameterId: 6,
      ParameterName: "Zoning",
      value: '"LR3"',
      Phase: "Site Information",
      ParameterTypeId: "1",
      ParamOrder: "8",
    },
    {
      ParameterId: 7,
      ParameterName: "MHA Suffix",
      value: '"M"',
      Phase: "Site Information",
      ParameterTypeId: "1",
      ParamOrder: "9",
    },
    {
      ParameterId: 8,
      ParameterName: "Assessed Value",
      value: '"500000"',
      Phase: "Site Information",
      ParameterTypeId: "2",
      ParamOrder: "11",
    },
    {
      ParameterId: 9,
      ParameterName: "Lot Width",
      value: '"100"',
      Phase: "Site Information",
      ParameterTypeId: "2",
      ParamOrder: "7",
    },
    {
      ParameterId: 10,
      ParameterName: "Lot Length",
      value: '"150"',
      Phase: "Site Information",
      ParameterTypeId: "2",
      ParamOrder: "6",
    },
    {
      ParameterId: 11,
      ParameterName: "High-end Area",
      value: '"Yes"',
      Phase: "Site Information",
      ParameterTypeId: "3",
      ParamOrder: "13",
    },
    {
      ParameterId: 12,
      ParameterName: "Major Arterial",
      value: '"Yes"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "3",
      ParamOrder: "21",
    },
    {
      ParameterId: 13,
      ParameterName: "Corner Lot",
      value: '"Yes"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "3",
      ParamOrder: "20",
    },
    {
      ParameterId: 14,
      ParameterName: "Alley",
      value: '"No"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "3",
      ParamOrder: "19",
    },
    {
      ParameterId: 15,
      ParameterName: "Growth Area",
      value: '"Yes"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "3",
      ParamOrder: "18",
    },
    {
      ParameterId: 16,
      ParameterName: "Elevation Change",
      value: '"20"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "2",
      ParamOrder: "15",
    },
    {
      ParameterId: 17,
      ParameterName: "Slope Direction",
      value: '"East to West"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "1",
      ParamOrder: "16",
    },
    {
      ParameterId: 18,
      ParameterName: "Tree Canopy Coverage",
      value: '"25%-50%"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "1",
      ParamOrder: "14",
    },
    {
      ParameterId: 19,
      ParameterName: "ECAs",
      value: '"Wetlands"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "4",
      ParamOrder: "22",
    },
    {
      ParameterId: 19,
      ParameterName: "ECAs",
      value: '"Riparian Corridor"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "4",
      ParamOrder: "22",
    },
    {
      ParameterId: 19,
      ParameterName: "ECAs",
      value: '"Potential Slide Area"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "4",
      ParamOrder: "22",
    },
    {
      ParameterId: 19,
      ParameterName: "ECAs",
      value: '"40% Steep Slope"',
      Phase: "Geographical Analysis",
      ParameterTypeId: "4",
      ParamOrder: "22",
    },
    {
      ParameterId: 20,
      ParameterName: "Water Main Extension",
      value: '"Yes"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "1",
      ParamOrder: "23",
    },
    {
      ParameterId: 21,
      ParameterName: "Water Main Length",
      value: '"200"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "2",
      ParamOrder: "24",
    },
    {
      ParameterId: 22,
      ParameterName: "Sewer Main Extension",
      value: '"Yes"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "1",
      ParamOrder: "25",
    },
    {
      ParameterId: 23,
      ParameterName: "Sewer Main Length",
      value: '"200"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "2",
      ParamOrder: "26",
    },
    {
      ParameterId: 24,
      ParameterName: "Alley Reconstruction",
      value: '"Yes"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "1",
      ParamOrder: "27",
    },
    {
      ParameterId: 25,
      ParameterName: "Alley Reconstruction Length",
      value: '"300"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "2",
      ParamOrder: "28",
    },
    {
      ParameterId: 26,
      ParameterName: "Underground Garage",
      value: '"Yes"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "3",
      ParamOrder: "32",
    },
    {
      ParameterId: 27,
      ParameterName: "Number of Spots",
      value: '"1"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "2",
      ParamOrder: "33",
    },
    {
      ParameterId: 29,
      ParameterName: "MHA Area",
      value: '"LOW"',
      Phase: "Site Information",
      ParameterTypeId: "1",
      ParamOrder: "10",
    },
    {
      ParameterId: 83,
      ParameterName: "Drainage Main",
      value: '"Yes"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "1",
      ParamOrder: "29",
    },
    {
      ParameterId: 84,
      ParameterName: "Drainage Distance",
      value: '"200"',
      Phase: "Utilities/Extras",
      ParameterTypeId: "1",
      ParamOrder: "30",
    },
  ],
  StructureTypes: [
    {
      StructureType: "Apartment",
      Calculations: [
        {
          ParameterId: "30",
          ParameterName: "Number of Homes",
          value: "3",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "36",
        },
        {
          ParameterId: "36",
          ParameterName: "Home Estimated Value",
          value: "1000000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "55",
        },
        {
          ParameterId: "41",
          ParameterName: "Sales Commission",
          value: "60000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "60",
        },
        {
          ParameterId: "42",
          ParameterName: "Excise Tax",
          value: "11900",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "61",
        },
        {
          ParameterId: "43",
          ParameterName: "Escrow Fees",
          value: "7500",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "63",
        },
        {
          ParameterId: "44",
          ParameterName: "Marketing and Staging",
          value: "5000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "64",
        },
        {
          ParameterId: "45",
          ParameterName: "Desired Profit Before Financing",
          value: "200000",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "65",
        },
        {
          ParameterId: "46",
          ParameterName: "Value of Land Per Home",
          value: "831199.8",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "66",
        },
        {
          ParameterId: "47",
          ParameterName: "Total Land Value",
          value: "2493599.4000000004",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "67",
        },
        {
          ParameterId: "50",
          ParameterName: "Profit Per Home before Financing",
          value: "831199.8",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "70",
        },
        {
          ParameterId: "55",
          ParameterName: "Equity",
          value: "200000",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "75",
        },
        {
          ParameterId: "56",
          ParameterName: "Acquisition Carrying Months",
          value: "12",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "76",
        },
        {
          ParameterId: "57",
          ParameterName: "Interest Rate Land Acquisition",
          value: "0.06",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "77",
        },
        {
          ParameterId: "58",
          ParameterName: "Total Financing Cost Land Acquisition",
          value: "160551.958",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "78",
        },
        {
          ParameterId: "59",
          ParameterName: "Interest Rate Construction Loan",
          value: "0.06",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "79",
        },
        {
          ParameterId: "60",
          ParameterName: "Loan Fees Construction Loan",
          value: "0.01",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "80",
        },
        {
          ParameterId: "61",
          ParameterName: "Construction Loan Months",
          value: "12",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "81",
        },
        {
          ParameterId: "62",
          ParameterName: "Total Financing Cost Construction",
          value: "2437120.8440000005",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "82",
        },
        {
          ParameterId: "64",
          ParameterName: "Months to Sell After completion",
          value: "2437120.8440000005",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "84",
        },
        {
          ParameterId: "65",
          ParameterName: "Extra Financing After Completion",
          value: "76929113473.98279",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "85",
        },
        {
          ParameterId: "66",
          ParameterName: "Total Financing Fees",
          value: "76931711146.78479",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "86",
        },
        {
          ParameterId: "67",
          ParameterName: "Sellable Square Footage",
          value: "4101.666666666667",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "42",
        },
        {
          ParameterId: "81",
          ParameterName: "Loan Fees Land Acquisition Loan",
          value: "0.01",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "100",
        },
        {
          ParameterId: "85",
          ParameterName: "Floor Area Ratio",
          value: "2.3",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "34",
        },
        {
          ParameterId: "86",
          ParameterName: "FAR Max",
          value: "11500",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "35",
        },
        {
          ParameterId: "87",
          ParameterName: "ECA Cost",
          value: "0",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "59",
        },
        {
          ParameterId: "88",
          ParameterName: "Elevation Grade Cost",
          value: "16666.666666666668",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "63",
        },
        {
          ParameterId: "89",
          ParameterName: "Water Line Cost",
          value: "66666.66666666667",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "65",
        },
        {
          ParameterId: "90",
          ParameterName: "Alley Cost",
          value: "50000",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "71",
        },
        {
          ParameterId: "91",
          ParameterName: "Sewer Cost",
          value: "66666.66666666667",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "67",
        },
        {
          ParameterId: "96",
          ParameterName: "Sellable Sqft Factor",
          value: "1.07",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "41",
        },
        {
          ParameterId: "99",
          ParameterName: "Townhome Base Cost",
          value: "1025416.6666666667",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "53",
        },
        {
          ParameterId: "105",
          ParameterName: "Storm Drain Cost",
          value: "66666.66666666667",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "69",
        },
        {
          ParameterId: "106",
          ParameterName: "Underground Parking Cost",
          value: "16666.666666666668",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "73",
        },
        {
          ParameterId: "108",
          ParameterName: "Total Project Cost",
          value: "4019515.0000000005",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "77",
        },
        {
          ParameterId: "110",
          ParameterName: "Townhome Base Cost Per Sqft",
          value: "250",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "46",
        },
        {
          ParameterId: "121",
          ParameterName: "MHA Cost",
          value: "31088.333333333332",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "74",
        },
        {
          ParameterId: "122",
          ParameterName: "Value of Land Per Home",
          value: "831199.8",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "123",
          ParameterName: "Total Land Value",
          value: "2493599.4000000004",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "127",
          ParameterName: "Total Building Cost Per Home",
          value: "1339838.3333333335",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "128",
          ParameterName: "Total Building Cost Per Home",
          value: "1339838.3333333335",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "136",
          ParameterName: "Total Sales Cost Per Home",
          value: "84400",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "137",
          ParameterName: "Total Sales Cost Per Home",
          value: "84400",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "140",
          ParameterName: "Total Sales Cost Per Project",
          value: "4019515.0000000005",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "141",
          ParameterName: "Total Sales Cost Per Project",
          value: "4019515.0000000005",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "155",
          ParameterName: "Profit For Project before Financing",
          value: "-7532629.400000002",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "157",
          ParameterName: "Net Profit Per Home",
          value: "-25645159153.728264",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "159",
          ParameterName: "Net Profit For Project",
          value: "-76939243776.18478",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "162",
          ParameterName: "Total Financing Cost",
          value: "76931711146.78479",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "27",
        },
        {
          ParameterId: "164",
          ParameterName: "Total Financing Cost Per Home",
          value: "25643903715.59493",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "18",
        },
        {
          ParameterId: "166",
          ParameterName: "Total Backend Sales Price",
          value: "3000000",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "23",
        },
        {
          ParameterId: "167",
          ParameterName: "Home Estimated Value",
          value: "1000000",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "2",
        },
        {
          ParameterId: "168",
          ParameterName: "Home Estimated Value",
          value: "1000000",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "2",
        },
        {
          ParameterId: "169",
          ParameterName: "Total Building Cost Per Home",
          value: "84400",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "6",
        },
        {
          ParameterId: "173",
          ParameterName: "Total Sales Cost Per Home",
          value: "84400",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "10",
        },
        {
          ParameterId: "178",
          ParameterName: "Total Project Cost",
          value: "2493599.4000000004",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "2",
        },
        {
          ParameterId: "179",
          ParameterName: "Total Land Value",
          value: "2493599.4000000004",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "1",
        },
        {
          ParameterId: "181",
          ParameterName: "Desired Profit Percent",
          value: "0.2",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "182",
          ParameterName: "Total Project Cost",
          value: "4019515.0000000005",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
      ],
    },
    {
      StructureType: "Rowhouse",
      Calculations: [
        {
          ParameterId: "30",
          ParameterName: "Number of Homes",
          value: "3",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "36",
        },
        {
          ParameterId: "36",
          ParameterName: "Home Estimated Value",
          value: "1000000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "55",
        },
        {
          ParameterId: "41",
          ParameterName: "Sales Commission",
          value: "60000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "60",
        },
        {
          ParameterId: "42",
          ParameterName: "Excise Tax",
          value: "11900",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "61",
        },
        {
          ParameterId: "43",
          ParameterName: "Escrow Fees",
          value: "7500",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "63",
        },
        {
          ParameterId: "44",
          ParameterName: "Marketing and Staging",
          value: "5000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "64",
        },
        {
          ParameterId: "45",
          ParameterName: "Desired Profit Before Financing",
          value: "200000",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "65",
        },
        {
          ParameterId: "46",
          ParameterName: "Value of Land Per Home",
          value: "831199.8",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "66",
        },
        {
          ParameterId: "47",
          ParameterName: "Total Land Value",
          value: "2493599.4000000004",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "67",
        },
        {
          ParameterId: "50",
          ParameterName: "Profit Per Home before Financing",
          value: "831199.8",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "70",
        },
        {
          ParameterId: "55",
          ParameterName: "Equity",
          value: "200000",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "75",
        },
        {
          ParameterId: "56",
          ParameterName: "Acquisition Carrying Months",
          value: "12",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "76",
        },
        {
          ParameterId: "57",
          ParameterName: "Interest Rate Land Acquisition",
          value: "0.06",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "77",
        },
        {
          ParameterId: "58",
          ParameterName: "Total Financing Cost Land Acquisition",
          value: "160551.958",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "78",
        },
        {
          ParameterId: "59",
          ParameterName: "Interest Rate Construction Loan",
          value: "0.06",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "79",
        },
        {
          ParameterId: "60",
          ParameterName: "Loan Fees Construction Loan",
          value: "0.01",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "80",
        },
        {
          ParameterId: "61",
          ParameterName: "Construction Loan Months",
          value: "12",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "81",
        },
        {
          ParameterId: "62",
          ParameterName: "Total Financing Cost Construction",
          value: "2437120.8440000005",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "82",
        },
        {
          ParameterId: "64",
          ParameterName: "Months to Sell After completion",
          value: "2437120.8440000005",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "84",
        },
        {
          ParameterId: "65",
          ParameterName: "Extra Financing After Completion",
          value: "76929113473.98279",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "85",
        },
        {
          ParameterId: "66",
          ParameterName: "Total Financing Fees",
          value: "76931711146.78479",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "86",
        },
        {
          ParameterId: "67",
          ParameterName: "Sellable Square Footage",
          value: "4101.666666666667",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "42",
        },
        {
          ParameterId: "81",
          ParameterName: "Loan Fees Land Acquisition Loan",
          value: "0.01",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "100",
        },
        {
          ParameterId: "85",
          ParameterName: "Floor Area Ratio",
          value: "2.3",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "34",
        },
        {
          ParameterId: "86",
          ParameterName: "FAR Max",
          value: "11500",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "35",
        },
        {
          ParameterId: "87",
          ParameterName: "ECA Cost",
          value: "0",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "59",
        },
        {
          ParameterId: "88",
          ParameterName: "Elevation Grade Cost",
          value: "16666.666666666668",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "63",
        },
        {
          ParameterId: "89",
          ParameterName: "Water Line Cost",
          value: "66666.66666666667",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "65",
        },
        {
          ParameterId: "90",
          ParameterName: "Alley Cost",
          value: "50000",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "71",
        },
        {
          ParameterId: "91",
          ParameterName: "Sewer Cost",
          value: "66666.66666666667",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "67",
        },
        {
          ParameterId: "96",
          ParameterName: "Sellable Sqft Factor",
          value: "1.07",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "41",
        },
        {
          ParameterId: "99",
          ParameterName: "Townhome Base Cost",
          value: "1025416.6666666667",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "53",
        },
        {
          ParameterId: "105",
          ParameterName: "Storm Drain Cost",
          value: "66666.66666666667",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "69",
        },
        {
          ParameterId: "106",
          ParameterName: "Underground Parking Cost",
          value: "16666.666666666668",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "73",
        },
        {
          ParameterId: "108",
          ParameterName: "Total Project Cost",
          value: "4019515.0000000005",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "77",
        },
        {
          ParameterId: "110",
          ParameterName: "Townhome Base Cost Per Sqft",
          value: "250",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "46",
        },
        {
          ParameterId: "121",
          ParameterName: "MHA Cost",
          value: "31088.333333333332",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "74",
        },
        {
          ParameterId: "122",
          ParameterName: "Value of Land Per Home",
          value: "831199.8",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "123",
          ParameterName: "Total Land Value",
          value: "2493599.4000000004",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "127",
          ParameterName: "Total Building Cost Per Home",
          value: "1339838.3333333335",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "128",
          ParameterName: "Total Building Cost Per Home",
          value: "1339838.3333333335",
          Phase: "Construction Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "136",
          ParameterName: "Total Sales Cost Per Home",
          value: "84400",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "137",
          ParameterName: "Total Sales Cost Per Home",
          value: "84400",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "140",
          ParameterName: "Total Sales Cost Per Project",
          value: "4019515.0000000005",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "141",
          ParameterName: "Total Sales Cost Per Project",
          value: "4019515.0000000005",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "155",
          ParameterName: "Profit For Project before Financing",
          value: "-7532629.400000002",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "157",
          ParameterName: "Net Profit Per Home",
          value: "-25645159153.728264",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "159",
          ParameterName: "Net Profit For Project",
          value: "-76939243776.18478",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "162",
          ParameterName: "Total Financing Cost",
          value: "76931711146.78479",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "27",
        },
        {
          ParameterId: "164",
          ParameterName: "Total Financing Cost Per Home",
          value: "25643903715.59493",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "18",
        },
        {
          ParameterId: "166",
          ParameterName: "Total Backend Sales Price",
          value: "3000000",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "23",
        },
        {
          ParameterId: "167",
          ParameterName: "Home Estimated Value",
          value: "1000000",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "2",
        },
        {
          ParameterId: "168",
          ParameterName: "Home Estimated Value",
          value: "1000000",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "2",
        },
        {
          ParameterId: "169",
          ParameterName: "Total Building Cost Per Home",
          value: "84400",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "6",
        },
        {
          ParameterId: "173",
          ParameterName: "Total Sales Cost Per Home",
          value: "84400",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "10",
        },
        {
          ParameterId: "178",
          ParameterName: "Total Project Cost",
          value: "2493599.4000000004",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "2",
        },
        {
          ParameterId: "179",
          ParameterName: "Total Land Value",
          value: "2493599.4000000004",
          Phase: "Financing",
          ParameterTypeId: "2",
          ParamOrder: "1",
        },
        {
          ParameterId: "181",
          ParameterName: "Desired Profit Percent",
          value: "0.2",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
        {
          ParameterId: "182",
          ParameterName: "Total Project Cost",
          value: "4019515.0000000005",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "999",
        },
      ],
    },
    {
      StructureType: "Townhome",
      Calculations: [
        {
          ParameterId: "30",
          ParameterName: "Number of Homes",
          value: "3",
          Phase: "Site Potential",
          ParameterTypeId: "2",
          ParamOrder: "36",
        },
        {
          ParameterId: "36",
          ParameterName: "Home Estimated Value",
          value: "1000000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "55",
        },
        {
          ParameterId: "41",
          ParameterName: "Sales Commission",
          value: "60000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "60",
        },
        {
          ParameterId: "42",
          ParameterName: "Excise Tax",
          value: "11900",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "61",
        },
        {
          ParameterId: "43",
          ParameterName: "Escrow Fees",
          value: "7500",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "63",
        },
        {
          ParameterId: "44",
          ParameterName: "Marketing and Staging",
          value: "5000",
          Phase: "Sales Cost Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "64",
        },
        {
          ParameterId: "45",
          ParameterName: "Desired Profit Before Financing",
          value: "200000",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "65",
        },
        {
          ParameterId: "46",
          ParameterName: "Value of Land Per Home",
          value: "831199.8",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "66",
        },
        {
          ParameterId: "47",
          ParameterName: "Total Land Value",
          value: "2493599.4000000004",
          Phase: "Land Analysis",
          ParameterTypeId: "2",
          ParamOrder: "67",
        },
        {
          ParameterId: "50",
          ParameterName: "Profit Per Home before Financing",
          value: "831199.8",
          Phase: "Proforma Breakdown",
          ParameterTypeId: "2",
          ParamOrder: "70",
        },
      ],
    },
  ],
};
